### ISSUE TITLE
Actividad 1

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-1-mapa-mental-edgarmauricio123#1]
Edgar Mauricio Sarmiento Ruiz Grupo 1BS
Actividad 1 Mapa investigación documental

![Mapa investigación documental](https://user-images.githubusercontent.com/112227375/187819183-cda19a19-acce-4f4f-8349-e97bbba8f43c.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 1 MAPA MENTAL
DE 20% DE LA ACTIVIDAD OBTUVISTE 17.8% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
